server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/chefmate
spring.datasource.username=chefmate
spring.datasource.password=chefmate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.application.name=chefmate-backend
spring.datasource.hikari.maximum-pool-size=5
spring.sql.init.mode=never

telegram.bot.token=${TELEGRAM_BOT_TOKEN:dummy-token}
telegram.bot.username=${TELEGRAM_BOT_USERNAME:dummy-bot}
telegram.bot.cook-id=${TELEGRAM_BOT_COOK_ID:0}
